name: Release Please

on:
  push:
    branches:
      - main

permissions: {}

jobs:
  release-please:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: googleapis/release-please-action@a02a34c4d625f9be7cb89156071d8567f2d26f77 # v4.2.0
